### ISSUE TITLE
分集的刮削 有bug 封面所有图片不显示 附上具体bug及建议

### ISSUE THREAD

**Issue by androiddisk** [mdc-ng/mdc_mbot_plugin#10]
![image](https://user-images.githubusercontent.com/11062371/222097954-77637dde-8b84-4b04-b565-b63cfd409b65.png)

如上图所示 我以为是刮削失败封面没下载
去文件夹看了几个 发现都有对应封面

![image](https://user-images.githubusercontent.com/11062371/222098201-84c16682-7561-40b0-ae47-5c2131b8c98e.png)

问题出在nfo里面
![image](https://user-images.githubusercontent.com/11062371/222098273-3e7b5755-ce0f-4b87-8285-aab7a68e0611.png)

下载下来的图片都带了CD1 CD2 但是nfo没带 所以就导致emby找不到图片

也许jelyfin不出这个bug吧。我是emby的 希望大佬修正一下

**Comment by androiddisk** [comment]
大佬能不能给个联系方式 我想加入组织

**Comment by androiddisk** [comment]
有个小小的建议 

我之前用的Movie_Data_Capture 刮削  FC2都会刮削到素人文件夹
目前的刮削 稍微有一点点乱 应该是找不到演员的原因吧。 建议找不到演员的番号全部单独的文件夹 FC2的找不到演员放素人文件夹 并且在演员表添加素人
![image](https://user-images.githubusercontent.com/11062371/222100510-45bf3384-1b36-41c2-b729-019592176464.png)

**Comment by mdc-ng** [comment]
> 

图片看起来是没有带CD part，nfo中路径也没带，是正确的。可能是emby没有根据nfo提供的文件名去找，我回去测试一下

**Comment by mdc-ng** [comment]
> 有个小小的建议
> 
> 我之前用的Movie_Data_Capture 刮削 FC2都会刮削到素人文件夹 目前的刮削 稍微有一点点乱 应该是找不到演员的原因吧。 建议找不到演员的番号全部单独的文件夹 FC2的找不到演员放素人文件夹 并且在演员表添加素人 ![image](https://user-images.githubusercontent.com/11062371/222100510-45bf3384-1b36-41c2-b729-019592176464.png)

默认情况找不到演员应该会统一放置到”未知演员“目录，但你提供的这个截图看起来甚至不是按演员分目录的？这个是插件刮削的结果吗

**Comment by androiddisk** [comment]
> > 有个小小的建议
> > 我之前用的Movie_Data_Capture 刮削 FC2都会刮削到素人文件夹 目前的刮削 稍微有一点点乱 应该是找不到演员的原因吧。 建议找不到演员的番号全部单独的文件夹 FC2的找不到演员放素人文件夹 并且在演员表添加素人 ![图像](https://user-images.githubusercontent.com/11062371/222100510-45bf3384-1b36-41c2-b729-019592176464.png)
> 
> 默认情况找不到演员应该会统一放置到”未知演员“目录，但你提供的这个截图看起来甚至不是按演员分目录的？这个是插件刮削的结果吗

是的 专门创建的一个测试目录 输出插件运行的刮削

**Comment by mdc-ng** [comment]
> > > 有个小小的建议
> > > 我之前用的Movie_Data_Capture 刮削 FC2都会刮削到素人文件夹 目前的刮削 稍微有一点点乱 应该是找不到演员的原因吧。 建议找不到演员的番号全部单独的文件夹 FC2的找不到演员放素人文件夹 并且在演员表添加素人 ![图像](https://user-images.githubusercontent.com/11062371/222100510-45bf3384-1b36-41c2-b729-019592176464.png)
> > 
> > 
> > 默认情况找不到演员应该会统一放置到”未知演员“目录，但你提供的这个截图看起来甚至不是按演员分目录的？这个是插件刮削的结果吗
> 
> 是的 专门创建的一个测试目录 输出插件运行的刮削

应该不会是你截图里的这个结构，找不到演员的会放置到“未知演员”，而不是直接丢到根目录。请描述一下测试方式，我需要复现一下

**Comment by androiddisk** [comment]
> > > > 有个小小的建议
> > > > 我之前用的Movie_Data_Capture 刮削 FC2都会刮削到素人文件夹 目前的刮削 稍微有一点点乱 应该是找不到演员的原因吧。 建议找不到演员的番号全部单独的文件夹 FC2的找不到演员放素人文件夹 并且在演员表添加素人 ![图像](https://user-images.githubusercontent.com/11062371/222100510-45bf3384-1b36-41c2-b729-019592176464.png)
> > > 
> > > 
> > > 默认情况找不到演员应该会统一放置到”未知演员“目录，但你提供的这个截图看起来甚至不是按演员分目录的？这个是插件刮削的结果吗
> > 
> > 
> > 是的 专门创建的一个测试目录 输出插件运行的刮削
> 
> 应该不会是你截图里的这个结构，找不到演员的会放置到“未知演员”，而不是直接丢到根目录。请描述一下测试方式，我需要复现一下

上次测试的时候 专门新建的文件夹呢 用于插件刮削输出

**Comment by mdc-ng** [comment]
默认设置下应该是按照演员加番号整理的，不会出现直接用番号的情况

可以发一下config.ini内容和版本号，我尝试复现一下。

**Comment by mdc-ng** [comment]
https://github.com/mdc-ng/mdc-ng/releases/tag/v0.15.0
![image](https://user-images.githubusercontent.com/124132602/223173609-3ad67650-a8a5-4950-9c80-dec0e5a982e0.png)

分CD图片问题在新版已修复，图片默认命名不再包含视频名称
