### ISSUE TITLE
番号名读取错误

### ISSUE THREAD

**Issue by androiddisk** [mdc-ng/mdc_mbot_plugin#11]
2023/03/01 19:50:24 - MBotExecutor_0 - INFO: [MDC] 开始处理视频文件: /video/测试/一ノ瀬アメリ/CPM-53/CPM-53.mp4
2023/03/01 19:50:24 - MBotExecutor_0 - INFO: [MDC] Version: v0.11.0
2023/03/01 19:50:24 - MBotExecutor_0 - INFO: [PM053] 番号识别结果: 'PM053'
2023/03/01 19:50:24 - MBotExecutor_0 - INFO: [PM053] 开始从以下[5]个站点并行抓取数据: ["madou", "javlibrary", "javbus", "airav", "mmtv"]
2023/03/01 19:50:24 - MBotExecutor_0 - INFO: [PM053] 未抓取到数据 <airav>: 未找到详情页
2023/03/01 19:50:24 - MBotExecutor_0 - INFO: [PM053] 未抓取到数据 <javbus>: 未找到详情页
2023/03/01 19:50:24 - MBotExecutor_0 - INFO: [PM053] 未抓取到数据 <javlibrary>: 未找到详情页
2023/03/01 19:50:25 - MBotExecutor_0 - INFO: [PM053] 未抓取到数据 <mmtv>: 未找到详情页
2023/03/01 19:50:25 - MBotExecutor_0 - INFO: [PM053] 未抓取到数据 <madou>: 未找到详情页
2023/03/01 19:50:25 - MBotExecutor_0 - INFO: [PM053] 元数据获取失败: Metadata key Number missed

**Comment by mdc-ng** [comment]
https://github.com/mdc-ng/mdc-ng/releases/tag/v0.13.1
更新最新server解决

**Comment by androiddisk** [comment]
好哒 您辛苦了
