### ISSUE TITLE
字幕未移动

### ISSUE THREAD

**Issue by androiddisk** [mdc-ng/mdc_mbot_plugin#12]
![image](https://user-images.githubusercontent.com/11062371/222140252-57cd64dc-36f3-4c22-8ada-2de2f405aba8.png)

**Comment by androiddisk** [comment]
字幕后面的.zh-CN导致了刮削检测不到 不确定您是否会认为是bug并修复 但我还是反馈下

**Comment by mdc-ng** [comment]
https://github.com/mdc-ng/mdc-ng/releases/tag/v0.15.1
已修复
