### ISSUE TITLE
v1.4.0版本MDC server进入设置报错

### ISSUE THREAD

**Issue by CN0579** [mdc-ng/mdc_mbot_plugin#14]
![80e88c2f26d34ca51c1e02e7642beaa](https://user-images.githubusercontent.com/37959510/222338646-c5394ed3-5e80-45e0-98ab-ab5bfaa0d215.png)

**Comment by CN0579** [comment]
![1677734984001](https://user-images.githubusercontent.com/37959510/222339344-a2d11708-dad6-482e-844b-a7e8492b1437.png)

**Comment by mdc-ng** [comment]
config.ini发一下

想解决这个问题可以把config删了让它自动生成一个默认的。水印部分重新配置一下

**Comment by CN0579** [comment]
[common]
target_folder = 

[proxy]
proxy = 

[watermark]
enabled = None
start = None
clockwise = None
poster = 1
thumb = 1
fanart = 0

**Comment by CN0579** [comment]
删除了config.ini的文件，问题依旧。

![image](https://user-images.githubusercontent.com/37959510/222341413-12fabbe8-8fe9-4d45-8f81-ddde2de91106.png)

**Comment by mdc-ng** [comment]
重新创建的config内容发一下

**Comment by CN0579** [comment]
[common]
target_folder = 

[proxy]
proxy = 

[watermark]
enabled = None
start = None
clockwise = None

**Comment by mdc-ng** [comment]
需要把config删掉，然后访问9208端口的web界面，让它生成config.ini。不要用插件的配置界面生成

**Comment by CN0579** [comment]
好的！我试试

**Comment by CN0579** [comment]
> 需要把config删掉，然后访问9208端口的web界面，让它生成config.ini。不要用插件的配置界面生成

好了！可以进去了
