### ISSUE TITLE
重启MR后,MDC server的config.ini会被插件生成的config.ini覆盖掉

### ISSUE THREAD

**Issue by CN0579** [mdc-ng/mdc_mbot_plugin#15]
重启MR后,MDC server的config.ini文件会被插件生成的config.ini覆盖掉

导致MDC server设置页面报错。

**Comment by mdc-ng** [comment]
https://github.com/mdc-ng/mdc_mbot_plugin/pull/16
1.4.1 在插件配置中移除了水印设置，后面不会再出现这个问题
