### ISSUE TITLE
v1.4.1重启MR后,MDC server的config.ini会被插件生成的config.ini覆盖掉

### ISSUE THREAD

**Issue by CN0579** [mdc-ng/mdc_mbot_plugin#17]
重启MR后,MDC server的config.ini会被插件生成的config.ini覆盖掉

重启后生成的config.ini如下：

[parser]
uncensored_prefixs = PT-,S2M,BT,LAF,SMD,SMBD,SM3D2DBD,SKY-,SKYHD,CWP,CWDV,CWBD,CW3D2DBD,MKD,MKBD,MXBD,MK3D2DBD,MCB3DBD,MCBD,RHJ,MMDV
sanitize_strings = 2048论坛@fun2048.com,1080p,720p,22-sht.me,-HD,bbs2048.org@,hhd800.com@,icao.me@,hhb_000,[456k.me],[ThZu.Cc],_U3C3,-hhb

[common]
target_folder = 

[download]
extra_fanarts = false
fanart = true
poster = true
thumb = true

[naming]
title = {number}-{title}
file = {number}
folder = {actor}/{number}

[proxy]
proxy = 
timeout = 10

[watermark]
poster = true
start = 0
fanart = false
enabled = true
clockwise = false
thumb = true

---------------------------------------------------------------------
导致进入MDC server设置报错

**Comment by mdc-ng** [comment]
target_folder没配导致的，可以在MR后台手动配一个

配置被MR覆盖是个bug，需要解决

**Comment by mdc-ng** [comment]
https://github.com/mdc-ng/mdc_mbot_plugin/pull/19
1.5.0后MR端的MDC使用独立配置，不再相互影响

**Comment by CN0579** [comment]
> #19 1.5.0后MR端的MDC使用独立配置，不再相互影响

1.5.0已经ok
