### ISSUE TITLE
影片分AB两段，刮削失败。

### ISSUE THREAD

**Issue by CN0579** [mdc-ng/mdc_mbot_plugin#21]
![1677851648672](https://user-images.githubusercontent.com/37959510/222737654-7453f44c-c4e2-4545-99ae-a618adac63bf.png)

**Comment by mdc-ng** [comment]
https://github.com/mdc-ng/mdc-ng/releases/tag/v0.15.0
![image](https://user-images.githubusercontent.com/124132602/223173239-2329517a-6c1b-4b3a-9e29-66839746bb44.png)

新版已修复
