### ISSUE TITLE
容器有映射media路劲，mr也有创建路劲，插件也有设置映射路劲跟实际路劲，后台看日志也有提示监控文件夹，就是下载下来不会自动刮削！求指点！

### ISSUE THREAD

**Issue by JDB2022888** [mdc-ng/mdc_mbot_plugin#22]
![微信截图_20230305144510](https://user-images.githubusercontent.com/107669928/222946212-f1da539e-0093-48aa-a3ff-cf8b59b96017.jpg)
![微信截图_20230305144546](https://user-images.githubusercontent.com/107669928/222946214-a469927a-37d1-42dc-abce-de7a2bf54103.jpg)
![微信截图_20230305144557](https://user-images.githubusercontent.com/107669928/222946216-a2d426f9-62c6-4384-af29-809953fd79c0.jpg)
容器有映射media路劲，mr也有创建路劲，插件也有设置映射路劲跟实际路劲，后台看日志也有提示监控文件夹，就是下载下来不会自动刮削！求指点！

**Comment by JDB2022888** [comment]
![1](https://user-images.githubusercontent.com/107669928/222946327-f2c944a2-4f93-4979-a91a-522020325cf2.png)
![2](https://user-images.githubusercontent.com/107669928/222946328-c46af971-ca77-4813-b284-b3c39aff68da.png)

**Comment by mdc-ng** [comment]
1. 圈出来的两个路径不匹配
2. 日志里面输出的监视文件夹比你设置的少一个，监视文件夹修改后重启MR
