### ISSUE TITLE
不自动刮削,监控目录设置求助!

### ISSUE THREAD

**Issue by JDB2022888** [mdc-ng/mdc_mbot_plugin#33]
![微信截图_20230312183852](https://user-images.githubusercontent.com/107669928/224539393-3c1b1d82-5f68-4da4-b65a-ebdacf86ee1d.png)
不自动刮削,监控目录设置求助!

**Comment by JDB2022888** [comment]
我现在实际目录为/downloads/AVYM-bot,映射目录为/media/AVYM-bot,下载完了不自动刮削硬连过去!求助!

**Comment by mdc-ng** [comment]
发下日志看下

**Comment by JDB2022888** [comment]
![微信截图_20230314151205](https://user-images.githubusercontent.com/107669928/224924128-15479944-8c77-4d75-8d99-df1c3c60ebe6.png)
![微信截图_20230314151247](https://user-images.githubusercontent.com/107669928/224924134-545ccd45-683d-4c17-ae13-6a903ad6683c.png)
![微信截图_20230314151622](https://user-images.githubusercontent.com/107669928/224924138-3e1060bd-d5f6-422e-a908-a465788aa4bd.png)
QB下载记录,插件运行日志,插件web页面搜索,显示都未刮削

**Comment by mdc-ng** [comment]
> ![微信截图_20230314151205](https://user-images.githubusercontent.com/107669928/224924128-15479944-8c77-4d75-8d99-df1c3c60ebe6.png)
> 
> ![微信截图_20230314151247](https://user-images.githubusercontent.com/107669928/224924134-545ccd45-683d-4c17-ae13-6a903ad6683c.png)
> 
> ![微信截图_20230314151622](https://user-images.githubusercontent.com/107669928/224924138-3e1060bd-d5f6-422e-a908-a465788aa4bd.png)
> 
> QB下载记录,插件运行日志,插件web页面搜索,显示都未刮削

日志中没有看到mr检测到下载，mr的媒体目录是否正确配置了？

**Comment by Kev1nT** [comment]
最近也遇到不刮削了，目录配置都没错，MR订阅下载没问题，但就是触发不了自动硬链和整理

**Comment by mdc-ng** [comment]
> 最近也遇到不刮削了，目录配置都没错，MR订阅下载没问题，但就是触发不了自动硬链和整理

日志里有MDC相关的吗

**Comment by Kev1nT** [comment]
> > 最近也遇到不刮削了，目录配置都没错，MR订阅下载没问题，但就是触发不了自动硬链和整理
> 
> 日志里有MDC相关的吗

我打开监控下载器任务就正常了，但是我以前不打开这个也是能自动刮的，但是能使用就不折腾了
