### ISSUE TITLE
缩略图下载失败导致硬连接失败

### ISSUE THREAD

**Issue by wxg1015** [mdc-ng/mdc_mbot_plugin#35]
任务列表明显可以看到已经识别成功了  但是下载图片失败   然后就无法硬链接  提示失败     但是实际上图片链接我复制到浏览器上是可以打开的  可以排除网络问题····
![photo_2023-03-13_16-13-01](https://user-images.githubusercontent.com/44153358/224644116-72c90950-e430-4a45-8ee3-597de9775f31.jpg)
![photo_2023-03-13_16-16-06](https://user-images.githubusercontent.com/44153358/224644364-46cff60e-1361-4b17-acc7-6f46ffb7e016.jpg)
![photo_2023-03-13_16-16-31](https://user-images.githubusercontent.com/44153358/224644380-6ac2b5a9-03db-4bec-9f7a-f23e76704b87.jpg)

**Comment by mdc-ng** [comment]
图片下载不了直接失败是预期行为，后面会考虑加上相关配置。另外错误信息表明是网络问题，可能是梯子不稳等原因，浏览器能访问不代表当时情况

**Comment by mdc-ng** [comment]
对网络原因于失败的条目，可以手动重试，一般都能成功
