### ISSUE TITLE
javbus跳验证

### ISSUE THREAD

**Issue by htnanako** [mdc-ng/mdc_mbot_plugin#44]
多部同时刮削时，javbus会跳年龄验证页面，导致刮削名变成了`Age Verification JavBus`
![image](https://github.com/mdc-ng/mdc_mbot_plugin/assets/68056603/5457373c-da31-444e-a099-28e25176df6e)

**Comment by mdc-ng** [comment]
https://github.com/mdc-ng/mdc-ng/releases/tag/v0.21.0
