### ISSUE TITLE
刮削插件可不可根据自定义订阅区分演员

### ISSUE THREAD

**Issue by lzhikaros** [mdc-ng/mdc_mbot_plugin#6]
比如我下一步相泽南，里面可能有其它女演员的场景，硬是成几个文件夹，可不可以都归纳到相泽南这一个文件夹里
![4FBDBC47-4CB8-4C8E-8F2A-B9A146FEC3A9](https://user-images.githubusercontent.com/58730620/218293763-0edee421-706a-443f-8a4d-7db67d364160.png)

**Comment by mdc-ng** [comment]
刮削出的信息没有“主演”这个概念，无法确定要刮到哪一个演员为主的目录中，这个需求需要再设计
