### ISSUE TITLE
可否设置不要下载剧照？

### ISSUE THREAD

**Issue by LeeHK1989** [mdc-ng/mdc_mbot_plugin#8]
应该有很多人和我一样只要在PLEX下能看到封面就行了。下载剧照占空间。同时也减轻一点网络访问量。

**Comment by mdc-ng** [comment]
1.4.0版后可以在MDC web中进行配置
![image](https://user-images.githubusercontent.com/124132602/222340398-de9aea2f-bc36-4abe-9961-5622c075ecec.png)

**Comment by LeeHK1989** [comment]
已经更新1.40，请问如何进入MDC WEB端？

**Comment by LeeHK1989** [comment]
> 已经更新1.40，请问如何进入MDC WEB端？

已经更新1.40，请问如何进入MDC WEB端？

> 1.4.0版后可以在MDC web中进行配置 ![image](https://user-images.githubusercontent.com/124132602/222340398-de9aea2f-bc36-4abe-9961-5622c075ecec.png)

已经更新1.40，请问如何进入MDC WEB端？

**Comment by LeeHK1989** [comment]
> 1.4.0版后可以在MDC web中进行配置 ![image](https://user-images.githubusercontent.com/124132602/222340398-de9aea2f-bc36-4abe-9961-5622c075ecec.png)

感谢，非常牛逼的刮削器，比之前用过的都好。
