### ISSUE TITLE
希望能同时监控多个目录!我愿意付费支持!

### ISSUE THREAD

**Issue by JDB2022888** [mdc-ng/mdc_mbot_plugin#9]
太牛了,真的是神一般的插件!
提一个小小的建议,如果能同时监控几个目录就完美了,例如,有码,无码,欧美,国产,那简直无敌了
这是我目前的分类目录
AV有码
AV无码
AV欧美
AV国产

**Comment by mdc-ng** [comment]
监控多个是可以的，配置中用逗号分割即可。但当前目标目录只支持配置一个

**Comment by JDB2022888** [comment]
感谢开发者的回复,监控多个目录我知道是可,可是刮削输出只能在一个目录,有点难受!
